site_name: Warframe Help
site_url: https://warframe.help/

nav:
  - Accueil: index.md
  - Débutant: 
    - beginner/index.md
    - Warframes: beginner/warframes.md
    - Armes: beginner/weapons.md
    - Compagnons: beginner/pets.md
    - Modding: beginner/mods.md
    - Carte Céleste: beginner/starchart.md
    - Quêtes: beginner/quests.md
    - Missions: beginner/missions.md
    - Rangs de Maîtrise: beginner/mastery-rank.md
    - Farm: beginner/farm.md
  - Steelpath: 
    - steelpath/index.md
    - Warframes: steelpath/warframes.md
    - Armes: steelpath/weapons.md
    - Compagnons: steelpath/pets.md
    - Armor-Strip: steelpath/armorstrip.md
    - Acolytes: steelpath/acolytes.md
    - Opérateur: steelpath/operator.md
    - Farm: steelpath/farm.md
    - Autres: steelpath/misc.md
  - Mods: mods.md
  - Checklist hebdomadaire : weekly-checklist.md
  - Références: content.md
  - About: about.md

theme:
  name: material
  language: fr
  logo: assets/logo.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: green

    # Light Mode
    - scheme: smooth-default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: light green 
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.indexes
    - toc.follow



extra:
  analytics:
    provider: google
    property: G-F0XRGZX4LE

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      

extra_css:
  - stylesheets/grid-links.css
  - stylesheets/themes.css
  - stylesheets/frontpage.css
  - https://rsms.me/inter/inter.css 